### ISSUE TITLE
create first block

### ISSUE THREAD

**Issue by basemain** [rhondle/BlockChain#1]
This is a wonderful program! Create the first block, I have to manually create two files? This program can do better applications?

**Comment by rhondle** [comment]
The program is intended as a working example of a real blockchain, it doesn't do anything more than that right now. It could be easily adapted for any use that you want, it just provides a starting point and a foundation for a project!

To create the firstblock:

``` php
if (!$res = addblock('blockchain.dat',
    'This is data that goes into the genesis block',
    true)) exit("Got error: ".$res."\n");
```

For additional blocks, be sure to set the `genesis` flag to false:

``` php
if (!$res = addblock('blockchain.dat',
    'This is an example of some arbitrary data for block #2'
    )) exit("Got error: ".$res."\n");
```

I will add a demo to the repo.

**Comment by basemain** [comment]
Thx. The php can build blockchain project?for example btc eth? Because now I saw c-btc java-nxt node-crypti blockchain project .

**Comment by rhondle** [comment]
It's certainly possible to build a cryptocurrency using PHP, yes. But I wouldn't necessarily recommend it unless a lot of research and planning has been done first, and there was a good reason to build yet another cryptocurrency.
